run_id: "C16_E16_H32_9" #"go6_cnn16_trf64" go2_cnn16_trf4_bs64_lr001, go2_newLR_lr0001_bs64_cnn16_trf16, Seed2lr0001_trf64_5

data:
  # use one of following or define a new task name in config_loader: 
  # "MetabolicState_2", "State_Modality_6", "State_Modality_Valence_16"
  task: "State_Modality_Valence_16" 
  split_strategy: "WithinAnimal"
  cache_images: false
  sequence:
    seq_len: 5
    seq_steps: 10
  augmentation:
    enabled: false
    num_augmentations: 5
  preprocessing:
    method_ch: 'meanZ'
    times: 'logTs'  #'logTs'
    neuropil: 'VMMP'
    remove_neuropil: false
    isolate_neuropil: true
    use_aligned_neuropil_template: false
    

    # splitting 
    # split-by one of following and adjust flags accordingly
    # ['S', 'F']
    # ['SO', 'FO', 'ST', 'FT', 'SM', 'FM']
    # ['SOP', 'SON', 'FOP', 'FON', 'STP', 'STN','FTP', 'FTN', 'SMMP', 'SMMN', 'SMCP', 'SMCN','FMMP', 'FMMN', 'FMCP', 'FMCN']
    split_by: ['S', 'F'] 
    exclude_controls: True
    include_StimType: False    
    include_MetaboliteState: True
    include_Valence: false
    train_startingFrame: 550
    val_test_proportion: 0.5
    resize: [128, 128]
    base_points: [0, 250]


model:
  architecture: "CNN_Transformer"
  parameters:
    nr_channels: 1
    cnn_embed_dim: 16
    transformer_embed_dim: 32
    max_seq_len: 10         # >= longest sequence you’ll feed
    num_heads: 2
    num_layers: 1
    dropout: 0.3

training:
  batch_size: 256
  epochs: 1000
  save_best_from: 100
  learning_rate: 0.001
  weight_decay: 0.0001 #0.0001 #0.00001
  criterion: "CrossEntropyLoss"
  num_workers: 8
  preload_to_ram: true
  shuffle_labels_naive: false
  shuffle_labels_consistantly: false 
  continue_training:
    resume: false
    until_epoch: 0

test_config:
  train_test_varying: false

base_seed: 777

paths:
  root: "/rhomes/aabdel/DrosoEmbedding"
  data_root: "/projects/lab-data/Collaboration/Gruenwald_Kadow"
  pickle_base: "pickles/TrainValTest_LocalScratch_Paths-Labels"
  allTs_base: "/localscratch/aabdel/imgs4DL"
  peakIDs_Times_All: '/rhomes/aabdel/MSc_DL4DrosoWBCI/pickles/IDs_logTs.pickle'

visualization:
  plot_batch_size: 16
  cam:
    method: "GradCAMPlusPlus"
    target_layer: 0
