run_id: "quickRun"

data:
  task: "State_Modality_6" # "MetabolicState_2", "State_Modality_6", "State_Modality_Valence_16"
  split_strategy: "WithinAnimal"
  neuropil: "WT"
  cache_images: false
  sequence:
    seq_len: 5
    seq_steps: 10
  augmentation:
    enabled: false
    num_augmentations: 5
  preprocessing:
    id: 'meanZ_allTs'
    split_by: ['SOP', 'SON', 'FOP', 'FON', 'STP', 'STN','FTP', 'FTN', 'SMMP', 'SMMN', 'SMCP', 'SMCN','FMMP', 'FMMN', 'FMCP', 'FMCN']
    exclude_controls: True
    include_StimType: True
    include_MetaboliteState: True
    include_Valence: True
    train_startingFrame: 550
    val_test_proportion: 0.5
    resize: [128, 128]
    knock_neuropil_out: false
    base_points: [0, 250]


model:
  architecture: "CNN_Transformer"
  parameters:
    nr_channels: 1
    embed_dim: 16
    num_heads: 2
    num_layers: 1
    dropout: 0.3

training:
  batch_size: 256
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.00001
  criterion: "CrossEntropyLoss"
  num_workers: 8

paths:
  root: "/rhomes/aabdel/DrosoEmbedding"
  data_root: "/projects/lab-data/Collaboration/Gruenwald_Kadow"
  pickle_base: "pickles/TrainValTest_LocalScratch_Paths-Labels"
  allTs_base: "/localscratch/aabdel/imgs4DL"

visualization:
  plot_batch_size: 16
  cam:
    method: "GradCAMPlusPlus"
    target_layer: 0
